### ISSUE TITLE
meterfs: problem if write is interrupted in narrow window

### ISSUE THREAD

**Issue by agkaminski** [phoenix-rtos/phoenix-rtos-filesystems#20]
If meterfs is terminated (proccess exit/power failure) after data has been written, but before id is written, next write will be corrupted.

Window:
between meterfs.c:343 and meterfs.c:344

**Comment by nalajcie** [comment]
was this taken care of or @Diabliz should look into it?

**Comment by pawelpisarczyk** [comment]
Guys, what happened with this?

**Comment by Diabliz** [comment]
I am going to take care, about it.

**Comment by agkaminski** [comment]
Solved in https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/61
